language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - android-23
env:
  global:
    - "MAVEN_OPTS=-Xmx3072m -XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:-UseGCOverheadLimit"
    - "TRAVIS_NODE_VERSION=6"
before_install:
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION"
  - "npm install"
  - "npm install electron-packager -g"
  - "npm install cordova -g"
  - "npm install bower -g"
  - "npm install vulcanize -g"
  - "git clone https://github.com/mirkosertic/teavm.git ./teavm"
  - "cd teavm"
  - "git checkout devmse"
  - "mvn clean install -DskipTests -Dteavm.build.all=false"
  - "cd .."
  - "env"
  - "echo 'MAVEN_OPTS = $MAVEN_OPTS'"
